package wyp;
// Generated 2016-05-30 11:24:48 by Hibernate Tools 4.3.1



/**
 * Autorzy generated by hbm2java
 */
public class Autorzy  implements java.io.Serializable {


     private Integer idAutora;
     private String imie;
     private String nazwisko;

    public Autorzy() {
    }

    public Autorzy(String imie, String nazwisko) {
       this.imie = imie;
       this.nazwisko = nazwisko;
    }
   
    public Integer getIdAutora() {
        return this.idAutora;
    }
    
    public void setIdAutora(Integer idAutora) {
        this.idAutora = idAutora;
    }
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }




}


