package wyp;
// Generated 2016-05-30 11:24:48 by Hibernate Tools 4.3.1



/**
 * Czytelnicy generated by hbm2java
 */
public class Czytelnicy  implements java.io.Serializable {


     private Integer idCzytelnika;
     private String imie;
     private String nazwisko;
     private String ulica;
     private String miasto;
     private String haslo;
     private boolean blokada;
     private float kara;
     private boolean aktywny;
     private int stopien;
     private String mail;

    public Czytelnicy() {
    }

    public Czytelnicy(String imie, String nazwisko, String ulica, String miasto, String haslo, boolean blokada, float kara, boolean aktywny, int stopien, String mail) {
       this.imie = imie;
       this.nazwisko = nazwisko;
       this.ulica = ulica;
       this.miasto = miasto;
       this.haslo = haslo;
       this.blokada = blokada;
       this.kara = kara;
       this.aktywny = aktywny;
       this.stopien = stopien;
       this.mail = mail;
    }
   
    public Integer getIdCzytelnika() {
        return this.idCzytelnika;
    }
    
    public void setIdCzytelnika(Integer idCzytelnika) {
        this.idCzytelnika = idCzytelnika;
    }
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }
    public String getUlica() {
        return this.ulica;
    }
    
    public void setUlica(String ulica) {
        this.ulica = ulica;
    }
    public String getMiasto() {
        return this.miasto;
    }
    
    public void setMiasto(String miasto) {
        this.miasto = miasto;
    }
    public String getHaslo() {
        return this.haslo;
    }
    
    public void setHaslo(String haslo) {
        this.haslo = haslo;
    }
    public boolean isBlokada() {
        return this.blokada;
    }
    
    public void setBlokada(boolean blokada) {
        this.blokada = blokada;
    }
    public float getKara() {
        return this.kara;
    }
    
    public void setKara(float kara) {
        this.kara = kara;
    }
    public boolean isAktywny() {
        return this.aktywny;
    }
    
    public void setAktywny(boolean aktywny) {
        this.aktywny = aktywny;
    }
    public int getStopien() {
        return this.stopien;
    }
    
    public void setStopien(int stopien) {
        this.stopien = stopien;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }




}


