package wyp;
// Generated 2016-05-30 11:24:48 by Hibernate Tools 4.3.1



/**
 * Kategorie generated by hbm2java
 */
public class Kategorie  implements java.io.Serializable {


     private Integer idKategori;
     private String nazwa;
     private Integer idRodzica;

    public Kategorie() {
    }

	
    public Kategorie(String nazwa) {
        this.nazwa = nazwa;
    }
    public Kategorie(String nazwa, Integer idRodzica) {
       this.nazwa = nazwa;
       this.idRodzica = idRodzica;
    }
   
    public Integer getIdKategori() {
        return this.idKategori;
    }
    
    public void setIdKategori(Integer idKategori) {
        this.idKategori = idKategori;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public Integer getIdRodzica() {
        return this.idRodzica;
    }
    
    public void setIdRodzica(Integer idRodzica) {
        this.idRodzica = idRodzica;
    }

}


