package wyp;
// Generated 2016-05-30 11:24:48 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * KolejkaId generated by hbm2java
 */
public class KolejkaId  implements java.io.Serializable {


     private int isbn;
     private int idCzytelnika;
     private Date dataZapisania;

    public KolejkaId() {
    }

    public KolejkaId(int isbn, int idCzytelnika, Date dataZapisania) {
       this.isbn = isbn;
       this.idCzytelnika = idCzytelnika;
       this.dataZapisania = dataZapisania;
    }
   
    public int getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(int isbn) {
        this.isbn = isbn;
    }
    public int getIdCzytelnika() {
        return this.idCzytelnika;
    }
    
    public void setIdCzytelnika(int idCzytelnika) {
        this.idCzytelnika = idCzytelnika;
    }
    public Date getDataZapisania() {
        return this.dataZapisania;
    }
    
    public void setDataZapisania(Date dataZapisania) {
        this.dataZapisania = dataZapisania;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof KolejkaId) ) return false;
		 KolejkaId castOther = ( KolejkaId ) other; 
         
		 return (this.getIsbn()==castOther.getIsbn())
 && (this.getIdCzytelnika()==castOther.getIdCzytelnika())
 && ( (this.getDataZapisania()==castOther.getDataZapisania()) || ( this.getDataZapisania()!=null && castOther.getDataZapisania()!=null && this.getDataZapisania().equals(castOther.getDataZapisania()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIsbn();
         result = 37 * result + this.getIdCzytelnika();
         result = 37 * result + ( getDataZapisania() == null ? 0 : this.getDataZapisania().hashCode() );
         return result;
   }   


}


