package wyp;
// Generated 2016-05-30 11:24:48 by Hibernate Tools 4.3.1



/**
 * Kolejka generated by hbm2java
 */
public class Kolejka  implements java.io.Serializable {


     private KolejkaId id;

    public Kolejka() {
    }

    public Kolejka(KolejkaId id) {
       this.id = id;
    }
   
    public KolejkaId getId() {
        return this.id;
    }
    
    public void setId(KolejkaId id) {
        this.id = id;
    }




}


