package wyp;
// Generated 2016-05-30 11:24:48 by Hibernate Tools 4.3.1



/**
 * KsiazkiAutorzy generated by hbm2java
 */
public class KsiazkiAutorzy  implements java.io.Serializable {


     private KsiazkiAutorzyId id;

    public KsiazkiAutorzy() {
    }

    public KsiazkiAutorzy(KsiazkiAutorzyId id) {
       this.id = id;
    }
   
    public KsiazkiAutorzyId getId() {
        return this.id;
    }
    
    public void setId(KsiazkiAutorzyId id) {
        this.id = id;
    }




}


