package wyp;
// Generated 2016-05-30 11:24:48 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ksiazki generated by hbm2java
 */
public class Ksiazki  implements java.io.Serializable {


     private int isbn;
     private String tytul;
     private int idKategori;
     private int stan;
     private int ilosc;
     private Date dataDodania;
     private int idWydawcy;
     private String opis;

    public Ksiazki() {
    }

	
    public Ksiazki(int isbn, String tytul, int idKategori, int stan, int ilosc, Date dataDodania, int idWydawcy) {
        this.isbn = isbn;
        this.tytul = tytul;
        this.idKategori = idKategori;
        this.stan = stan;
        this.ilosc = ilosc;
        this.dataDodania = dataDodania;
        this.idWydawcy = idWydawcy;
    }
    public Ksiazki(int isbn, String tytul, int idKategori, int stan, int ilosc, Date dataDodania, int idWydawcy, String opis) {
       this.isbn = isbn;
       this.tytul = tytul;
       this.idKategori = idKategori;
       this.stan = stan;
       this.ilosc = ilosc;
       this.dataDodania = dataDodania;
       this.idWydawcy = idWydawcy;
       this.opis = opis;
    }
   
    public int getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(int isbn) {
        this.isbn = isbn;
    }
    public String getTytul() {
        return this.tytul;
    }
    
    public void setTytul(String tytul) {
        this.tytul = tytul;
    }
    public int getIdKategori() {
        return this.idKategori;
    }
    
    public void setIdKategori(int idKategori) {
        this.idKategori = idKategori;
    }
    public int getStan() {
        return this.stan;
    }
    
    public void setStan(int stan) {
        this.stan = stan;
    }
    public int getIlosc() {
        return this.ilosc;
    }
    
    public void setIlosc(int ilosc) {
        this.ilosc = ilosc;
    }
    public Date getDataDodania() {
        return this.dataDodania;
    }
    
    public void setDataDodania(Date dataDodania) {
        this.dataDodania = dataDodania;
    }
    public int getIdWydawcy() {
        return this.idWydawcy;
    }
    
    public void setIdWydawcy(int idWydawcy) {
        this.idWydawcy = idWydawcy;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }




}


