package wyp;
// Generated 2016-05-30 11:24:48 by Hibernate Tools 4.3.1



/**
 * KsiazkiAutorzyId generated by hbm2java
 */
public class KsiazkiAutorzyId  implements java.io.Serializable {


     private int isbn;
     private int idAutora;

    public KsiazkiAutorzyId() {
    }

    public KsiazkiAutorzyId(int isbn, int idAutora) {
       this.isbn = isbn;
       this.idAutora = idAutora;
    }
   
    public int getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(int isbn) {
        this.isbn = isbn;
    }
    public int getIdAutora() {
        return this.idAutora;
    }
    
    public void setIdAutora(int idAutora) {
        this.idAutora = idAutora;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof KsiazkiAutorzyId) ) return false;
		 KsiazkiAutorzyId castOther = ( KsiazkiAutorzyId ) other; 
         
		 return (this.getIsbn()==castOther.getIsbn())
 && (this.getIdAutora()==castOther.getIdAutora());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIsbn();
         result = 37 * result + this.getIdAutora();
         return result;
   }   


}


