package wyp;
// Generated 2016-05-30 11:24:48 by Hibernate Tools 4.3.1



/**
 * PlikiId generated by hbm2java
 */
public class PlikiId  implements java.io.Serializable {


     private String nazwa;
     private int isbn;

    public PlikiId() {
    }

    public PlikiId(String nazwa, int isbn) {
       this.nazwa = nazwa;
       this.isbn = isbn;
    }
   
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public int getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(int isbn) {
        this.isbn = isbn;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlikiId) ) return false;
		 PlikiId castOther = ( PlikiId ) other; 
         
		 return ( (this.getNazwa()==castOther.getNazwa()) || ( this.getNazwa()!=null && castOther.getNazwa()!=null && this.getNazwa().equals(castOther.getNazwa()) ) )
 && (this.getIsbn()==castOther.getIsbn());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNazwa() == null ? 0 : this.getNazwa().hashCode() );
         result = 37 * result + this.getIsbn();
         return result;
   }   


}


