package wyp;
// Generated 2016-05-30 11:24:48 by Hibernate Tools 4.3.1



/**
 * Pliki generated by hbm2java
 */
public class Pliki  implements java.io.Serializable {


     private PlikiId id;
     private String roz;

    public Pliki() {
    }

    public Pliki(PlikiId id, String roz) {
       this.id = id;
       this.roz = roz;
    }
   
    public PlikiId getId() {
        return this.id;
    }
    
    public void setId(PlikiId id) {
        this.id = id;
    }
    public String getRoz() {
        return this.roz;
    }
    
    public void setRoz(String roz) {
        this.roz = roz;
    }




}


