package wyp;
// Generated 2016-05-30 11:24:48 by Hibernate Tools 4.3.1



/**
 * TagiK generated by hbm2java
 */
public class TagiK  implements java.io.Serializable {


     private TagiKId id;

    public TagiK() {
    }

    public TagiK(TagiKId id) {
       this.id = id;
    }
   
    public TagiKId getId() {
        return this.id;
    }
    
    public void setId(TagiKId id) {
        this.id = id;
    }




}


