package wyp;
// Generated 2016-05-30 11:24:48 by Hibernate Tools 4.3.1



/**
 * TagiKId generated by hbm2java
 */
public class TagiKId  implements java.io.Serializable {


     private int idTagu;
     private int isbn;

    public TagiKId() {
    }

    public TagiKId(int idTagu, int isbn) {
       this.idTagu = idTagu;
       this.isbn = isbn;
    }
   
    public int getIdTagu() {
        return this.idTagu;
    }
    
    public void setIdTagu(int idTagu) {
        this.idTagu = idTagu;
    }
    public int getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(int isbn) {
        this.isbn = isbn;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TagiKId) ) return false;
		 TagiKId castOther = ( TagiKId ) other; 
         
		 return (this.getIdTagu()==castOther.getIdTagu())
 && (this.getIsbn()==castOther.getIsbn());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTagu();
         result = 37 * result + this.getIsbn();
         return result;
   }   


}


