package wyp;
// Generated 2016-05-30 11:24:48 by Hibernate Tools 4.3.1



/**
 * Tagi generated by hbm2java
 */
public class Tagi  implements java.io.Serializable {


     private Integer idTagu;
     private String nazwa;

    public Tagi() {
    }

    public Tagi(String nazwa) {
       this.nazwa = nazwa;
    }
   
    public Integer getIdTagu() {
        return this.idTagu;
    }
    
    public void setIdTagu(Integer idTagu) {
        this.idTagu = idTagu;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }




}


