package wyp;
// Generated 2016-05-30 11:24:48 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Wiadomosci generated by hbm2java
 */
public class Wiadomosci  implements java.io.Serializable {


     private Integer idWiadomosci;
     private String tytul;
     private String tresc;
     private Date data;

    public Wiadomosci() {
    }

    public Wiadomosci(String tytul, String tresc, Date data) {
       this.tytul = tytul;
       this.tresc = tresc;
       this.data = data;
    }
   
    public Integer getIdWiadomosci() {
        return this.idWiadomosci;
    }
    
    public void setIdWiadomosci(Integer idWiadomosci) {
        this.idWiadomosci = idWiadomosci;
    }
    public String getTytul() {
        return this.tytul;
    }
    
    public void setTytul(String tytul) {
        this.tytul = tytul;
    }
    public String getTresc() {
        return this.tresc;
    }
    
    public void setTresc(String tresc) {
        this.tresc = tresc;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }




}


