package wyp;
// Generated 2016-05-30 11:24:48 by Hibernate Tools 4.3.1



/**
 * Wydawcy generated by hbm2java
 */
public class Wydawcy  implements java.io.Serializable {


     private Integer idWydawcy;
     private String nazwa;

    public Wydawcy() {
    }

    public Wydawcy(String nazwa) {
       this.nazwa = nazwa;
    }
   
    public Integer getIdWydawcy() {
        return this.idWydawcy;
    }
    
    public void setIdWydawcy(Integer idWydawcy) {
        this.idWydawcy = idWydawcy;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }




}


