package wyp;
// Generated 2016-05-30 11:24:48 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Wypozyczenia generated by hbm2java
 */
public class Wypozyczenia  implements java.io.Serializable {


     private WypozyczeniaId id;
     private Date dataOddania;
     private int status;

    public Wypozyczenia() {
    }

	
    public Wypozyczenia(WypozyczeniaId id, int status) {
        this.id = id;
        this.status = status;
    }
    public Wypozyczenia(WypozyczeniaId id, Date dataOddania, int status) {
       this.id = id;
       this.dataOddania = dataOddania;
       this.status = status;
    }
   
    public WypozyczeniaId getId() {
        return this.id;
    }
    
    public void setId(WypozyczeniaId id) {
        this.id = id;
    }
    public Date getDataOddania() {
        return this.dataOddania;
    }
    
    public void setDataOddania(Date dataOddania) {
        this.dataOddania = dataOddania;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


